const menu = [
  {
    id: 1,
    name: "Pizza",
    price: 20.99,
    category: "Italian",
    img: "https://static.vecteezy.com/system/resources/thumbnails/022/994/039/small/the-pepperoni-pizza-and-a-piece-of-streched-cheese-pizza-with-ai-generated-free-photo.jpg",
  },
  {
    id: 2,
    name: "Burger",
    price: 15.99,
    category: "American",
    img: "https://static.vecteezy.com/system/resources/thumbnails/024/065/637/small/juicy-hamburger-with-bokeh-background-delicious-fast-food-illustration-ai-generated-free-photo.jpg",
  },
  {
    id: 3,
    name: "Pasta",
    price: 18.5,
    category: "Italian",
    img: "https://static.vecteezy.com/system/resources/thumbnails/040/491/366/small/ai-generated-classic-pasta-on-kitchen-background-diet-and-food-concept-photo.jpeg",
  },
  {
    id: 4,
    name: "Salad",
    price: 12.99,
    category: "Healthy",
    img: "https://static.vecteezy.com/system/resources/thumbnails/011/436/970/small/tomato-salad-vegetable-healthy-meal-food-snack-diet-on-the-table-copy-space-food-background-rustic-top-view-keto-or-paleo-diet-veggie-vegan-or-vegetarian-food-photo.jpg",
  },
  {
    id: 5,
    name: "Steak",
    price: 25.99,
    category: "American",
    img: "https://static.vecteezy.com/system/resources/thumbnails/033/196/663/small/beef-ribeye-steak-grilling-on-a-flaming-grill-generative-ai-free-photo.jpg",
  },
  {
    id: 6,
    name: "Sushi",
    price: 22.5,
    category: "Japanese",
    img: "https://static.vecteezy.com/system/resources/thumbnails/023/291/691/small/the-japanese-sushi-set-on-the-wood-plate-with-ai-generated-free-photo.jpg",
  },
  {
    id: 7,
    name: "Sandwich",
    price: 10.99,
    category: "American",
    img: "https://static.vecteezy.com/system/resources/thumbnails/024/851/314/small/microgreens-sandwich-salad-with-bread-for-a-healthy-lifestyle-generative-ai-photo.jpg",
  },
  {
    id: 8,
    name: "Soup",
    price: 8.99,
    category: "Healthy",
    img: "https://static.vecteezy.com/system/resources/thumbnails/030/323/009/small/delicious-tom-yum-soup-dish-in-thailand-restaurant-generative-ai-photo.jpg",
  },
  {
    id: 9,
    name: "Fish and Chips",
    price: 16.99,
    category: "Seafood",
    img: "https://static.vecteezy.com/system/resources/thumbnails/030/602/825/small/fish-and-chips-macro-ai-generative-photo.jpg",
  },
  {
    id: 10,
    name: "Tacos",
    price: 14.5,
    category: "Mexican",
    img: "https://static.vecteezy.com/system/resources/thumbnails/023/575/931/small/the-mexican-tacos-on-the-wood-plate-with-ai-generated-free-photo.jpg",
  },
  {
    id: 11,
    name: "Chicken Wings",
    price: 13.99,
    category: "American",
    img: "https://static.vecteezy.com/system/resources/thumbnails/030/323/120/small/appetizing-fried-chicken-fried-delicious-chicken-wings-grilled-food-generative-ai-photo.jpg",
  },
  {
    id: 12,
    name: "Burrito",
    price: 17.5,
    category: "Mexican",
    img: "https://static.vecteezy.com/system/resources/thumbnails/024/068/276/small/hearty-breakfast-burrito-with-scrambled-eggs-veggies-and-beans-ai-generated-free-photo.jpg",
  },
  {
    id: 13,
    name: "Ramen",
    price: 11.99,
    category: "Japanese",
    img: "https://static.vecteezy.com/system/resources/thumbnails/036/433/453/small/ai-generated-a-bowl-of-hot-noodle-soup-on-wooden-table-generative-ai-photo.jpg",
  },
  {
    id: 14,
    name: "Shrimp Scampi",
    price: 19.99,
    category: "Seafood",
    img: "https://media.istockphoto.com/id/1414307299/photo/closeup-garlic-butter-shrimp-in-pan.jpg?s=612x612&w=0&k=20&c=4J1w6K8W-bL8yJSioQVoPVGT9pipj3IcimSExRRQbm4=",
  },
  {
    id: 15,
    name: "Lasagna",
    price: 21.5,
    category: "Italian",
    img: "https://cdn.evbuc.com/images/724238529/267487093900/1/logo.20240320-162316",
  },
  {
    id: 16,
    name: "Calzone",
    price: 16.99,
    category: "Italian",
    img: "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F499367069%2F1287852147943%2F1%2Foriginal.20230424-101121?h=200&w=512&auto=format%2Ccompress&q=75&sharp=10&rect=0%2C106%2C1280%2C640&s=1ea707e7c253a2e6935acc8cdfc29c01",
  },
  {
    id: 17,
    name: "Fish Tacos",
    price: 18.99,
    category: "Mexican",
    img: "https://www.shutterstock.com/image-photo/mexican-fish-tacos-metal-tray-260nw-1762885340.jpg",
  },
  {
    id: 18,
    name: "Hot Dog",
    price: 7.5,
    category: "American",
    img: "https://static.vecteezy.com/system/resources/thumbnails/023/291/549/small/the-delicious-hotdog-in-the-black-background-with-ai-generated-free-photo.jpg",
  },
  {
    id: 19,
    name: "Margarita Pizza",
    price: 18.99,
    category: "Italian",
    img: "https://media.istockphoto.com/id/1280329631/photo/italian-pizza-margherita-with-tomatoes-and-mozzarella-cheese-on-wooden-cutting-board-close-up.jpg?s=612x612&w=0&k=20&c=CFDDjavIC5l8Zska16UZRZDXDwd47fwmRsUNzY0Ym6o=",
  },
  {
    id: 20,
    name: "Caesar Salad",
    price: 14.5,
    category: "Healthy",
    img: "https://img.freepik.com/free-photo/front-view-tasty-vegetable-salad-inside-plate-with-fork-dark-background_179666-19405.jpg",
  },
  {
    id: 21,
    name: "Taco Salad",
    price: 14.99,
    category: "Mexican",
    img: "https://media.gettyimages.com/id/882558246/photo/beef-taco-salad.jpg?s=170667a&w=gi&k=20&c=NQOK6s0qe-X9x2AtgkTeLWZ_-Aq45dsDrrArAuE64xk=",
  },
  {
    id: 22,
    name: "Tempura",
    price: 19.99,
    category: "Japanese",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6PisVoHA460oAAmI-28PYTkCPxw6WWHZe2zOG8EPUHg&s",
  },
  {
    id: 23,
    name: "Grilled Salmon",
    price: 22.99,
    category: "Seafood",
    img: "https://static.vecteezy.com/system/resources/thumbnails/024/692/099/small/ai-generated-ai-generative-illustration-of-bbq-grilled-fresh-baked-steak-salmon-with-salad-graphic-art-photo.jpg",
  },
  {
    id: 24,
    name: "Quinoa Salad",
    price: 13.5,
    category: "Healthy",
    img: "https://media.istockphoto.com/id/937016542/photo/quinoa-salad-with-beet-root-and-spinach.jpg?s=612x612&w=0&k=20&c=hI7X9AzPWGtiusK8NZs7qF1rmJTjHrsmKilFkQgkZs8=",
  },
  {
    id: 25,
    name: "Enchiladas",
    price: 16.99,
    category: "Mexican",
    img: "https://bloximages.chicago2.vip.townnews.com/simcoe.com/content/tncms/assets/v3/editorial/2/da/2da4fbfa-e2d1-5d31-9b0d-785408db141f/63d85a8faf940.image.jpg?resize=400%2C200",
  },
  {
    id: 26,
    name: "Sushi Roll",
    price: 18.5,
    category: "Japanese",
    img: "https://static.vecteezy.com/system/resources/thumbnails/033/481/960/small/sushi-on-a-white-plate-and-on-a-wooden-table-on-a-white-backdrop-ai-generative-photo.jpeg",
  },
  {
    id: 27,
    name: "Shrimp Cocktail",
    price: 17.5,
    category: "Seafood",
    img: "https://media.istockphoto.com/id/155278893/photo/cocktail-shrimp-with-avocado-salsa.jpg?s=612x612&w=0&k=20&c=Fu9KD65R4mvAPBvxa985J9xJoUj1awwH97D2ZweK7oc=",
  },
  {
    id: 28,
    name: "Quinoa Bowl",
    price: 15.99,
    category: "Healthy",
    img: "https://media.istockphoto.com/id/944540212/photo/buddha-bowl-quinoa-chicken-avocado-carrot-broccoli-for-the-summer.jpg?s=612x612&w=0&k=20&c=8nMmiUzeTiJ7e1IOlryoveFyYhZkRT0-8Gc2jZ_p8Uo=",
  },
  {
    id: 29,
    name: "Fish Tostadas",
    price: 19.99,
    category: "Mexican",
    img: "https://www.shutterstock.com/image-photo/tostadas-de-ceviche-mexican-food-260nw-134396777.jpg",
  },
  {
    id: 30,
    name: "Sashimi Platter",
    price: 25.99,
    category: "Japanese",
    img: "https://t4.ftcdn.net/jpg/05/84/01/37/360_F_584013720_d8BjliFfvtzN9tQwP47Ar4x0uYZUwqKY.jpg",
  },
];

export default menu;
